require("hamza.core.keymap")
require("hamza.core.options")
require("hamza.core.theme")

require("hamza.plugins.fugitive")
require("hamza.plugins.gitsigns")
require("hamza.plugins.harpoon")
require("hamza.plugins.lsp")
require("hamza.plugins.lualine")
require("hamza.plugins.nvim_comment")
require("hamza.plugins.telescope")
require("hamza.plugins.treesitter")
require("hamza.plugins.treesitter_context")
